reddit/reddit_clone/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:create, :destroy]
  resources :subs 
  resources :posts, except: [:index]
  
  root to: "subs#index"
end

reddit/reddit_clone/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

reddit/reddit_clone/app/models/post.rb
class Post < ApplicationRecord
  validates :title, :author_id, presence: true 

  # has many post_subs, DD-destroys in the post_subs if this is deleted
  # inverse of says create same association with sub
  has_many :post_subs, 
  dependent: :destroy, 
  inverse_of: :post,
  foreign_key: :post_id,
  primary_key: :id,
  class_name: :PostSub


  has_many :subs,
  through: :post_subs,
  source: :sub

  belongs_to :author,
  class_name: :User
end

reddit/reddit_clone/app/models/post_sub.rb
class PostSub < ApplicationRecord
  # validates :post_id, :sub_id, presence: true

  belongs_to :post
  belongs_to :sub

end

reddit/reddit_clone/app/models/sub.rb
class Sub < ApplicationRecord
  validates :title, :description, presence: true

  belongs_to :moderator,
  primary_key: :id,
  foreign_key: :moderator_id,
  class_name: :User

  has_many :post_subs, dependent: :destroy, inverse_of: :sub

  has_many :posts,
  through: :post_subs,
  source: :post

end

reddit/reddit_clone/app/models/user.rb
class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  
  attr_reader :password

  after_initialize :ensure_session_token

  has_many :subs

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

end

reddit/reddit_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in? 

  def login(user)
    session[:session_token] = user.reset_session_token!
    @current_user = user
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to subs_url unless logged_in?
  end

end

reddit/reddit_clone/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new  
    @post = Post.new
  end

  def create 
    
    @post = Post.new(post_params)
    @post.author_id = current_user.id
    if @post.save!
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def show  
    @post = Post.find(params[:id])
  end
  
  def edit   
    @post = Post.find(params[:id])
  end

  def update  
    @post = current_user.posts(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def destroy  
    
  end

  def post_params 
    params.require(:post).permit(:title, :url, :content, sub_ids: [])
  end
end

reddit/reddit_clone/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # def new

  # end
  
  def create 
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to request.referrer
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to request.referrer
    end
  end

  def destroy 
    logout
    redirect_to subs_url
  end
  
end

reddit/reddit_clone/app/controllers/subs_controller.rb
class SubsController < ApplicationController

before_action :require_login, only: [:edit, :new, :create, :update]
before_action :require_mod, only: [:edit, :update]

  def new 
    @sub = Sub.new
  end

  def create 
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def index 
    @subs = Sub.all
  end 

  def show 
    @sub = Sub.find(params[:id])
    # debugger
  end
  
  def edit 
    @sub = Sub.find(params[:id])
  end
  
  def update 
    # debugger 
    @sub = Sub.find(params[:id])
    @sub.moderator_id = current_user.id
    if @sub.update_attributes(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end
  
  def require_mod
    @sub = Sub.find(params[:id])
    redirect_to sub_url(@sub) unless current_user.id == @sub.moderator_id
  end

  def sub_params
    params.require(:sub).permit(:title, :description)
  end

end

reddit/reddit_clone/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show 
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

reddit/reddit_clone/app/helpers/application_helper.rb
module ApplicationHelper
  def auth
    "<input type='hidden' name='authenticity_token' value='#{form_authenticity_token}'>".html_safe
  end
end

reddit/reddit_clone/app/helpers/posts_helper.rb
module PostsHelper
end

reddit/reddit_clone/app/helpers/sessions_helper.rb
module SessionsHelper
end

reddit/reddit_clone/app/helpers/subs_helper.rb
module SubsHelper
end

reddit/reddit_clone/app/helpers/users_helper.rb
module UsersHelper
end

reddit/reddit_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditClone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>


  <body>
    <% if logged_in? %>
      <%= current_user.username %>
      <form action="<%= session_url %>" method="post">
        <%= auth %>
        <input type="hidden" name="_method" value="delete">
        <input type="submit" value="Sign Out">
      </form>
    <%else%>
      <form action="<%=session_url%>" method="post">
        <%= auth %>
        <label>Username
          <input type="text" name="user[username]">
        </label>
        <br>
        <label>Password
          <input type="text" name="user[password]">
        </label>
        <input type="submit" value="Sign In">
      </form>

      <a href="<%= new_user_url %>">Sign Up</a>

    <%end%>
    <%= yield %>
  </body>
</html>

reddit/reddit_clone/app/views/posts/new.html.erb
<h2>Create New Post!</h2>

<form action="<%= posts_url %>" method="post">
    <%= auth %>
    <label>Title
      <input type="text" name="post[title]">
    </label>
    <label>URL
      <input type="text" name="post[url]">
    </label>
    <br>
    <label>Content
      <textarea name="post[content]" cols="60" rows="5"><%= @post.content %></textarea>
    </label>
    <ul>
      <% Sub.all.each do |sub| %>
        <li>
          <input type="checkbox" name="post[sub_ids][]" value="<%= sub.id %>"><%=sub.title%>
        </li>  
      <% end %>
    </ul>


    <input type="submit" value="Create Post">
</form>

reddit/reddit_clone/app/views/posts/show.html.erb
<a href="<%=subs_url%>">All Subs</a>

<h2><%= @post.title %></h2>
<h5><%= @post.author.username %></h5>
<div>
  <label>Post Text:  
    <p><%= @post.content %></p>
  </label>
  <% if @post.url.length > 0 %>
    <a href="<%= @post.url %>"><%= @post.url %></a>
  <% end %>
</div>

reddit/reddit_clone/app/views/subs/edit.html.erb
<h2>Edit Sub!</h2>

<form action="<%= sub_url(@sub) %>" method="post">
    <input type="hidden" name="_method" value="patch">
    <%= auth %>
    <label>Title
      <input type="text" name="sub[title]" value="<%= @sub.title %>">
    </label>
    <br>
    <label>Description
      <textarea name="sub[description]" cols="60" rows="5"><%= @sub.description %></textarea>
    </label>
    <input type="submit" value="Edit Sub">
</form>

reddit/reddit_clone/app/views/subs/index.html.erb
<h2>All of the Subs!</h2>
<br>
<a href="<%=new_sub_url%>">Add a Sub</a>
<br>
<% @subs.each do |sub| %>
  <ul>
    <li>
      <a href="<%=sub_url(sub)%>"><%=sub.title%></a>
    </li>
  </ul>
<%end%>

reddit/reddit_clone/app/views/subs/new.html.erb
<h2>Create New Sub!</h2>

<form action="<%= subs_url %>" method="post">
    <%= auth %>
    <label>Title
      <input type="text" name="sub[title]">
    </label>
    <br>
    <label>Description
      <textarea name="sub[description]" cols="60" rows="5"><%= @sub.description %></textarea>
    </label>
    <input type="submit" value="Create Sub">
</form>

reddit/reddit_clone/app/views/subs/show.html.erb
<h2>Sub: <%= @sub.title %></h2>
<a href="<%= edit_sub_url(@sub) %>">Edit Sub</a>

<div class="description"">
  <p><%= @sub.description %></p>
</div>

<a href="<%= new_post_url %>">Create a Post</a>
<br>
<a href="<%= subs_url %>">Back to All Subs</a>
<br>
<h3>All Posts</h3>
<ul>
    <% @sub.posts.each do |post| %>
    <li>
      <a href="<%= post_url(post) %>"><%= post.title %></a>
      <span>Posted by: <%= post.author.username %>.</span>
    </li>
    <% end %>
</ul>

reddit/reddit_clone/app/views/users/new.html.erb
<h2>Create a User</h2>

<form action="<%= users_url %>" method="post">
    <%= auth %>
    <label>Username
      <input type="text" name="user[username]">
    </label>
    <br>
    <label>Password
      <input type="text" name="user[password]">
    </label>
    <input type="submit" value="New User">
</form>

reddit/reddit_clone/app/views/users/show.html.erb
"users show page"